apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-frontend
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{.Release.Name}}-backend"}]'
spec:
  revisionHistoryLimit: 0
  replicas: 4
  selector:
    matchLabels:
      app: {{.Release.Name}}-frontend
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: sikalabs/slu:v0.88.0
          args:
            - /bin/sh
            - -c
            - slu wait-for tcp -a {{.Release.Name}}-backend:80
      containers:
        - name: frontend
          image: ghcr.io/ondrejsika/counter-frontend
          env:
            - name: API_ORIGIN
              value: "http://{{.Release.Name}}-backend"
            - name: FONT_COLOR
              value: {{ .Values.frontend.FONT_COLOR }}
            - name: BACKGROUND_COLOR
              value: {{ .Values.frontend.BACKGROUND_COLOR }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          startupProbe:
            httpGet:
              path: /api/livez
              port: 3000
          livenessProbe:
            httpGet:
              path: /api/livez
              port: 3000
